"""Initial migration

Revision ID: 2155b0e78aa7
Revises: 
Create Date: 2025-09-26 23:28:57.499399

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2155b0e78aa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('account_status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='accountstatus'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('primary_role', sa.Enum('ADMIN', 'NUTRITIONIST', 'PATIENT', 'SUPPORT', name='userrole'), nullable=False),
    sa.Column('secondary_roles', sa.JSON(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_failed_login', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'NUTRITIONIST', 'PATIENT', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatus'), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('changed_fields', sa.JSON(), nullable=True),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('common_names', sa.JSON(), nullable=True),
    sa.Column('category', sa.Enum('CEREALS', 'VEGETABLES', 'FRUITS', 'LEGUMES', 'ANIMAL_PRODUCTS', 'FATS', 'SUGARS', 'FREE_FOODS', 'DAIRY', 'BEVERAGES', name='foodcategory'), nullable=False),
    sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('base_unit', sa.Enum('GRAMS', 'MILLILITERS', 'PIECES', 'CUPS', 'TABLESPOONS', 'TEASPOONS', 'SLICES', name='measurementunit'), nullable=False),
    sa.Column('serving_size', sa.Float(), nullable=False),
    sa.Column('calories_per_serving', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('sugar_g', sa.Float(), nullable=False),
    sa.Column('sodium_mg', sa.Float(), nullable=False),
    sa.Column('vitamins', sa.JSON(), nullable=True),
    sa.Column('minerals', sa.JSON(), nullable=True),
    sa.Column('glycemic_index', sa.Integer(), nullable=True),
    sa.Column('allergens', sa.JSON(), nullable=True),
    sa.Column('dietary_flags', sa.JSON(), nullable=True),
    sa.Column('disease_modifiers', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('APPROVED', 'PENDING', 'REJECTED', name='foodstatus'), nullable=False),
    sa.Column('proposed_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('seasonal_availability', sa.JSON(), nullable=True),
    sa.Column('average_cost_per_kg', sa.Float(), nullable=True),
    sa.Column('search_keywords', sa.JSON(), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_name'), 'foods', ['name'], unique=False)
    op.create_table('nutritionists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('university', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('specializations', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('clinic_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('clinic_address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('consultation_fee', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', name='verificationstatus'), nullable=False),
    sa.Column('verification_documents', sa.JSON(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('available_for_new_patients', sa.Boolean(), nullable=False),
    sa.Column('max_patients', sa.Integer(), nullable=True),
    sa.Column('consultation_modes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('user_role_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'NUTRITIONIST', 'PATIENT', 'SUPPORT', name='userrole'), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['auth_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_assignments_role'), 'user_role_assignments', ['role'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_user_id'), 'user_role_assignments', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('share_profile', sa.Boolean(), nullable=False),
    sa.Column('share_progress', sa.Boolean(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('food_equivalents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('cereal_exchanges', sa.Float(), nullable=False),
    sa.Column('vegetable_exchanges', sa.Float(), nullable=False),
    sa.Column('fruit_exchanges', sa.Float(), nullable=False),
    sa.Column('legume_exchanges', sa.Float(), nullable=False),
    sa.Column('meat_exchanges', sa.Float(), nullable=False),
    sa.Column('fat_exchanges', sa.Float(), nullable=False),
    sa.Column('milk_exchanges', sa.Float(), nullable=False),
    sa.Column('portion_for_exchange', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_equivalents_food_id'), 'food_equivalents', ['food_id'], unique=False)
    op.create_table('nutritionist_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutritionist_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('consultation_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('break_between_consultations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nutritionist_id'], ['nutritionists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutritionist_availability_nutritionist_id'), 'nutritionist_availability', ['nutritionist_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=False),
    sa.Column('active_nutritionist_id', sa.Integer(), nullable=True),
    sa.Column('primary_goal', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('target_body_fat_pct', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.Enum('SEDENTARY', 'LIGHTLY_ACTIVE', 'MODERATELY_ACTIVE', 'VERY_ACTIVE', 'EXTREMELY_ACTIVE', name='activitylevel'), nullable=False),
    sa.Column('occupation', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('share_feed', sa.Boolean(), nullable=False),
    sa.Column('allow_data_research', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['active_nutritionist_id'], ['nutritionists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('anthropometric_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('muscle_mass_kg', sa.Float(), nullable=True),
    sa.Column('bone_mass_kg', sa.Float(), nullable=True),
    sa.Column('water_pct', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('hip_cm', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('arm_cm', sa.Float(), nullable=True),
    sa.Column('thigh_cm', sa.Float(), nullable=True),
    sa.Column('triceps_mm', sa.Float(), nullable=True),
    sa.Column('biceps_mm', sa.Float(), nullable=True),
    sa.Column('subscapular_mm', sa.Float(), nullable=True),
    sa.Column('suprailiac_mm', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('waist_hip_ratio', sa.Float(), nullable=True),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('measured_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['measured_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anthropometric_records_patient_id'), 'anthropometric_records', ['patient_id'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('nutritionist_id', sa.Integer(), nullable=False),
    sa.Column('consultation_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('consultation_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('subjective_notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('objective_notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('assessment', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('dietary_recommendations', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('lifestyle_recommendations', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('next_appointment', sa.Date(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nutritionist_id'], ['nutritionists.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_nutritionist_id'), 'consultations', ['nutritionist_id'], unique=False)
    op.create_index(op.f('ix_consultations_patient_id'), 'consultations', ['patient_id'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('daily_calories_target', sa.Float(), nullable=False),
    sa.Column('daily_protein_target', sa.Float(), nullable=False),
    sa.Column('daily_carbs_target', sa.Float(), nullable=False),
    sa.Column('daily_fat_target', sa.Float(), nullable=False),
    sa.Column('generated_by', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('approved_by_nutritionist', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_patient_id'), 'meal_plans', ['patient_id'], unique=False)
    op.create_table('medical_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('intolerances', sa.JSON(), nullable=True),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('family_history', sa.JSON(), nullable=True),
    sa.Column('lab_results', sa.JSON(), nullable=True),
    sa.Column('lab_date', sa.Date(), nullable=True),
    sa.Column('eating_preferences', sa.JSON(), nullable=True),
    sa.Column('food_aversions', sa.JSON(), nullable=True),
    sa.Column('dietary_restrictions', sa.JSON(), nullable=True),
    sa.Column('smoking', sa.Boolean(), nullable=False),
    sa.Column('alcohol_consumption', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('emergency_contact_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('emergency_contact_relationship', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('nutritional_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('daily_calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('potassium_mg', sa.Float(), nullable=True),
    sa.Column('calcium_mg', sa.Float(), nullable=True),
    sa.Column('iron_mg', sa.Float(), nullable=True),
    sa.Column('condition_adjustments', sa.JSON(), nullable=True),
    sa.Column('calculation_method', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('calculation_details', sa.JSON(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutritional_goals_patient_id'), 'nutritional_goals', ['patient_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('author_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('author_patient_id', sa.Integer(), nullable=True),
    sa.Column('author_nutritionist_id', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Enum('VERY_EASY', 'EASY', 'MEDIUM', 'HARD', 'VERY_HARD', name='difficultylevel'), nullable=False),
    sa.Column('instructions', sa.JSON(), nullable=True),
    sa.Column('cooking_tips', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('meal_types', sa.JSON(), nullable=True),
    sa.Column('cuisine_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('dietary_tags', sa.JSON(), nullable=True),
    sa.Column('suitable_for_conditions', sa.JSON(), nullable=True),
    sa.Column('allergen_warnings', sa.JSON(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_protein_g', sa.Float(), nullable=True),
    sa.Column('total_carbs_g', sa.Float(), nullable=True),
    sa.Column('total_fat_g', sa.Float(), nullable=True),
    sa.Column('total_fiber_g', sa.Float(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', name='recipestatus'), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('rating_average', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_recipe_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_nutritionist_id'], ['nutritionists.id'], ),
    sa.ForeignKeyConstraint(['author_patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['parent_recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_title'), 'recipes', ['title'], unique=False)
    op.create_table('meal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'MORNING_SNACK', 'LUNCH', 'AFTERNOON_SNACK', 'DINNER', 'EVENING_SNACK', name='mealtype'), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('recipe_servings', sa.Float(), nullable=True),
    sa.Column('ad_hoc_items', sa.JSON(), nullable=True),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('consumption_notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('actual_items', sa.JSON(), nullable=True),
    sa.Column('planned_calories', sa.Float(), nullable=True),
    sa.Column('actual_calories', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_entries_meal_plan_id'), 'meal_entries', ['meal_plan_id'], unique=False)
    op.create_table('recipe_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('preparation', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_items_food_id'), 'recipe_items', ['food_id'], unique=False)
    op.create_index(op.f('ix_recipe_items_recipe_id'), 'recipe_items', ['recipe_id'], unique=False)
    op.create_table('recipe_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('helpful_votes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ratings_recipe_id'), 'recipe_ratings', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_recipe_ratings_user_id'), 'recipe_ratings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_ratings_user_id'), table_name='recipe_ratings')
    op.drop_index(op.f('ix_recipe_ratings_recipe_id'), table_name='recipe_ratings')
    op.drop_table('recipe_ratings')
    op.drop_index(op.f('ix_recipe_items_recipe_id'), table_name='recipe_items')
    op.drop_index(op.f('ix_recipe_items_food_id'), table_name='recipe_items')
    op.drop_table('recipe_items')
    op.drop_index(op.f('ix_meal_entries_meal_plan_id'), table_name='meal_entries')
    op.drop_table('meal_entries')
    op.drop_index(op.f('ix_recipes_title'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_nutritional_goals_patient_id'), table_name='nutritional_goals')
    op.drop_table('nutritional_goals')
    op.drop_table('medical_histories')
    op.drop_index(op.f('ix_meal_plans_patient_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_consultations_patient_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_nutritionist_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_anthropometric_records_patient_id'), table_name='anthropometric_records')
    op.drop_table('anthropometric_records')
    op.drop_table('patients')
    op.drop_index(op.f('ix_nutritionist_availability_nutritionist_id'), table_name='nutritionist_availability')
    op.drop_table('nutritionist_availability')
    op.drop_index(op.f('ix_food_equivalents_food_id'), table_name='food_equivalents')
    op.drop_table('food_equivalents')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_role_assignments_user_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_role'), table_name='user_role_assignments')
    op.drop_table('user_role_assignments')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('nutritionists')
    op.drop_index(op.f('ix_foods_name'), table_name='foods')
    op.drop_table('foods')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###